name: build

on: [ push, pull_request ]

concurrency: ${{ github.ref }}

jobs:
  build-plugin:
    name: 'Install & Build UI Plugin'
    runs-on: ubuntu-latest

    env:
      PLUGIN_FOLDER: Resources/Private/InspectorView

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.PLUGIN_FOLDER }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: actions/setup-node@v3
        with:
          node-version-file: '${{ env.PLUGIN_FOLDER }}/.nvmrc'

      - name: 'yarn install'
        run: yarn
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        working-directory: ${{ env.PLUGIN_FOLDER }}

      - name: 'yarn build'
        run: yarn build
        working-directory: ${{ env.PLUGIN_FOLDER }}
